function cam_calibration_loadimages_Callback(~, ~, ~)
handles=gui.gethand;
[cam_selected_target_images,location]=uigetfile(...
	{'*.bmp;*.tif;*.tiff;*.jpg;*.png','Image files';
	'*.bmp','Bitmaps'; ...
	'*.tif;*.tiff','TIF'; ...
	'*.jpg','JPEG'; ...
	'*.png','PNG'; ...
	'*.*',  'All Files'}...
	,"MultiSelect","on",'Select images of the calibration target',gui.retr('pathname'));
if ~isempty(cam_selected_target_images)
	pathfiles=fullfile(location,cam_selected_target_images);
	gui.put('cam_selected_target_images',pathfiles)
	handles.calib_usecalibration.Value = 0;
    gui.put('cam_use_calibration',0);
    if gui.retr('stereomode') == 1
        stereo.store_current_camera_state();
    end
end
