function settings_Callback(~, ~, ~)
%SETTINGS_CALLBACK Show Stereo-PIV scaffold status.

stereo_session = stereo.init_gui_state();
message = { ...
	'Stereo-PIV scaffold initialized.'; ...
	['Session status: ' stereo_session.status]; ...
	'Implemented in this patch: configuration/session structs, stereo state persistence, command-line entry points, and API placeholders.'; ...
	'TODO: add GUI panels, paired import UX, stereo calibration, disparity correction, and 2D3C reconstruction.'};
gui.custom_msgbox('msg', getappdata(0, 'hgui'), 'Stereo PIV', message, 'modal', {'OK'}, 'OK');
end
