function [path, multitiff] = select_image_files(pathname, prompt_text)
%SELECT_IMAGE_FILES Open the standard PIVlab image picker.

if nargin < 2 || isempty(prompt_text)
	prompt_text = 'Select images. Images from one set should have identical dimensions to avoid problems.';
end

if nargin < 1 || isempty(pathname)
	pathname = pwd;
end

if ~verLessThan('matlab','25')
	if ispc==1
		try
			[path, multitiff] = gui.uipickfiles( ...
				'FilterSpec', pathname, ...
				'REFilter', '\.bmp$|\.jpg$|\.png$|\.tif$|\.jpeg$|\.tiff$|\.b16$', ...
				'numfiles', [1 inf], ...
				'output', 'struct', ...
				'prompt', prompt_text);
		catch
			[path, multitiff] = gui.uipickfiles( ...
				'FilterSpec', pwd, ...
				'REFilter', '\.bmp$|\.jpg$|\.png$|\.tif$|\.jpeg$|\.tiff$|\.b16$', ...
				'numfiles', [1 inf], ...
				'output', 'struct', ...
				'prompt', prompt_text);
		end
	else
		try
			[path, multitiff] = gui.uipickfiles( ...
				'FilterSpec', pathname, ...
				'REFilter', '\.bmp$|\.jpg$|\.png$|\.tif$|\.jpeg$|\.tiff$|\.b16$', ...
				'numfiles', [1 inf], ...
				'output', 'struct', ...
				'prompt', prompt_text);
		catch
			[path, multitiff] = gui.uipickfiles( ...
				'FilterSpec', pwd, ...
				'numfiles', [1 inf], ...
				'output', 'struct', ...
				'prompt', prompt_text);
		end
	end
else
	if ispc==1
		try
			[path, multitiff] = gui.uipickfiles_pre_2025( ...
				'FilterSpec', pathname, ...
				'REFilter', '\.bmp$|\.jpg$|\.png$|\.tif$|\.jpeg$|\.tiff$|\.b16$', ...
				'numfiles', [1 inf], ...
				'output', 'struct', ...
				'prompt', prompt_text);
		catch
			[path, multitiff] = gui.uipickfiles_pre_2025( ...
				'FilterSpec', pwd, ...
				'REFilter', '\.bmp$|\.jpg$|\.png$|\.tif$|\.jpeg$|\.tiff$|\.b16$', ...
				'numfiles', [1 inf], ...
				'output', 'struct', ...
				'prompt', prompt_text);
		end
	else
		try
			[path, multitiff] = gui.uipickfiles_pre_2025( ...
				'FilterSpec', pathname, ...
				'REFilter', '\.bmp$|\.jpg$|\.png$|\.tif$|\.jpeg$|\.tiff$|\.b16$', ...
				'numfiles', [1 inf], ...
				'output', 'struct', ...
				'prompt', prompt_text);
		catch
			[path, multitiff] = gui.uipickfiles_pre_2025( ...
				'FilterSpec', pwd, ...
				'numfiles', [1 inf], ...
				'output', 'struct', ...
				'prompt', prompt_text);
		end
	end
end
end
