title: Leap Day theme
description: Leap Day is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
collections:
  wiki:
    output: true
    permalink: /wiki/:path/
nav:
  - title: "Home"
    url: "/PIVlab/"
  - title: "About"
    url: "/PIVlab/about.html"
  - title: "Wiki"
    url: "/PIVlab/wiki/"